TestWeb/Controllers/PDFController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestWeb.Controllers
{
    public class PDFController : Controller
    {
      // GET: PDF
      public ActionResult Local()
      {
         return View();
      }

      public ActionResult Stream()
      {
         return View();
      }

      public ActionResult UseDemo()
      {

         try
         {
            FileStream readPdf = new FileStream(Request.PhysicalApplicationPath + @"\customerData\BBB.pdf", FileMode.Open);
            long fileSize = readPdf.Length;
            byte[] bufferArray = new byte[fileSize];
            readPdf.Read(bufferArray, 0, (int)fileSize);
            readPdf.Close();

            string base64Str = Convert.ToBase64String(bufferArray);

            var viewModel = new PdfViewModel
            {
               PDF = base64Str
            };

            return View(viewModel);
         }
         catch (Exception ex)
         {
            return BadRequest();
         }


      }

      public ActionResult UseDemo2()
      {
         return View();
      }

      [HttpPost]
      public string getPdfStream(string args)
      {
         var returnstr = new { success = "false", message = "", data = "" };//返回值

         try
         {
            FileStream readPdf = new FileStream(Request.PhysicalApplicationPath + @"\customerData\BBB.pdf", FileMode.Open);
            long fileSize = readPdf.Length;
            byte[] bufferArray = new byte[fileSize];
            readPdf.Read(bufferArray, 0, (int)fileSize);
            readPdf.Close();

            string base64Str = Convert.ToBase64String(bufferArray);

            returnstr = new { success = "true", message = "", data = base64Str };

            return JsonConvert.SerializeObject(returnstr);
         }
         catch (Exception ex)
         {
            returnstr = new { success = "false", message = "异常信息如下：" + ex.Message, data = "" };
            return JsonConvert.SerializeObject(returnstr);
         }
      }

      protected ActionResult BadRequest()
      {
         return Redirect("~/400.html");
      }

   }

   public class PdfViewModel
   {
      public string PDF { get; set; }
   }
}

TestWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li>@Html.ActionLink("Home", "Index", "Home")</li>
						<li>@Html.ActionLink("Moneris", "Index", "Moneris")</li>
						<li>@Html.ActionLink("PDF Local", "Local", "PDF")</li>
						<li>@Html.ActionLink("PDF Stream", "Stream", "PDF")</li>
						<li>@Html.ActionLink("PDF Use DEMO", "UseDemo", "PDF")</li>
						<li>@Html.ActionLink("PDF Use DEMO2", "UseDemo2", "PDF")</li>
					</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>